'use strict';

/* ═══════════════════════════════════════════════════════════
   site-lang.js — Fashiontv Magazine Ana Site Çok Dil Desteği
   TR / EN / RU
   localStorage key: 'ftv_site_lang'
   ═══════════════════════════════════════════════════════════ */

const LANGS = {

  /* ─────────────────── TÜRKÇE ─────────────────── */
  tr: {
    /* Nav */
    'nav.home':       'Ana Sayfa',
    'nav.news':       'Haberler',
    'nav.about':      'Hakkımızda',
    'nav.sub':        'Abonelik',
    'nav.contact':    'İletişim',
    'nav.login':      'Giriş Yap',
    'nav.logout':     'Çıkış Yap',
    'nav.account':    'Hesabım',

    /* Footer */
    'footer.tagline':       'Modanın, güzelliğin ve yaşam sanatının buluştuğu premium editorial platform.',
    'footer.col.discover':  'Keşfet',
    'footer.col.corporate': 'Kurumsal',
    'footer.col.membership':'Üyelik',
    'footer.issue':         'Bu Ayın Sayısı',
    'footer.fashion':       'Moda',
    'footer.beauty':        'Güzellik',
    'footer.life':          'Yaşam',
    'footer.trends':        'Trendler',
    'footer.interviews':    'Özel Röportajlar',
    'footer.about':         'Hakkımızda',
    'footer.ads':           'Reklam & Medya',
    'footer.career':        'Kariyer',
    'footer.contact':       'İletişim',
    'footer.press':         'Basın',
    'footer.plans':         'Planlar',
    'footer.gift':          'Hediye Aboneliği',
    'footer.archive':       'Dijital Arşiv',
    'footer.design':        'Dergi Tasarla',
    'footer.support':       'Destek',
    'footer.copy':          '© 2026 Fashiontv Magazine. Tüm hakları saklıdır.',
    'footer.privacy':       'Gizlilik Politikası',
    'footer.terms':         'Kullanım Koşulları',
    'footer.cookie':        'Çerez',

    /* ── ANASAYFA ── */
    'home.hero.label':         'fashiontv magazine',
    'home.hero.title':         'Moda, Güzellik<br><em>& Yaşam Sanatı</em>',
    'home.hero.sub':           'Podyumdan yaşama — lüks ve stilin buluştuğu premium dergi.',
    'home.hero.btn.issue':     'Güncel Sayı',
    'home.hero.btn.sub':       'Abone Ol',

    'home.editorial.label':    'Fashiontv Magazine',
    'home.editorial.title':    'Modayı sadece takip etmeyin,<br>onun bir parçası olun',
    'home.editorial.text':     'Fashiontv Magazine; moda, güzellik, kültür ve yaşam stilini bir araya getiren seçkin bir editoryal deneyim sunar. Her sayı; ilham veren görseller, güçlü hikâyeler ve zamansız estetik anlayışıyla hazırlanır.',
    'home.editorial.feat1':    'Özel editoryal içerikler',
    'home.editorial.feat2':    'Premium dergi deneyimi',
    'home.editorial.feat3':    'Dijital ve yaratıcı tasarım alanı',
    'home.editorial.btn.dark': 'Bu Ayın Sayısı',
    'home.editorial.btn.sub':  'Aboneliği İncele',

    'home.issue.label':          'Güncel Sayı',
    'home.issue.heading':      'fashiontv magazine <br><em>Nisan Sayısı Çıktı</em>',
    'home.issue.body':         'Bu ayki özel sayımızda dünyanın en prestijli isimlerinden eksiksiz röportajlar, 2026 ilkbahar–yaz koleksiyonlarının derinlemesine analizi ve modanın geleceğini şekillendiren vizyoner tasarımcılar sizi bekliyor.',
    'home.issue.li1':          '12 Eksiksiz Röportaj',
    'home.issue.li2':          '40+ Sayfa Özel Editorial',
    'home.issue.li3':          'Koleksiyon Analizi & Trendler',
    'home.issue.btn':          'Hemen Abone Ol',

    'home.cats.label':         'Keşfet',
    'home.cats.heading':       'Kategoriler',
    'home.cat1.name':          'Moda',
    'home.cat1.desc':          'Koleksiyonlar & stil rehberleri',
    'home.cat2.name':          'Güzellik',
    'home.cat2.desc':          'Beauty editorials',
    'home.cat3.name':          'Yaşam',
    'home.cat3.desc':          'Lüks yaşam & kültür',
    'home.cat4.name':          'Trendler',
    'home.cat4.desc':          'Sezonun yönü',
    'home.cat5.name':          'Özel Röportajlar',
    'home.cat5.desc':          'Modanın ikonları',

    'home.casting.eyebrow':    'fashiontv magazine casting',
    'home.casting.title':      'Model, Manken ya da<br>Oyuncu olmak ister misiniz?',
    'home.casting.desc':       'Başvurunuzu oluşturun, ekibimiz incelesin. Onaylandıktan sonra ilanınız binlerce profesyonele ulaşsın — ücretsiz.',
    'home.casting.btn.apply':  'Hemen Başvur',
    'home.casting.btn.browse': 'Casting\'i Keşfet',

    'home.featured.label':     'Öne Çıkanlar',
    'home.featured.heading':   'Editörün Seçimi',
    'home.featured.all':       'Tümünü Gör →',
    'home.read.more':          'Devamını Oku',

    'home.design.label':       'Yaratıcı Araç',
    'home.design.heading':     'Kapak Yıldızımız Sensin!<br /><em>Röportaja Hazır Mısın?</em>',
    'home.design.body':        'Fashiontv Magazine\'in güçlü tasarım platformuyla kendi editöryal kapağını oluştur. Profesyonel şablonlar, kurumsal marka kiti ve baskıya hazır çıktı seni bekliyor.',
    'home.design.feat1':       '50+ Premium Şablon',
    'home.design.feat2':       'Kurumsal Brand Kiti',
    'home.design.feat3':       'Baskıya Hazır 300 DPI Çıktı',
    'home.design.btn':         'Tasarlamaya Başla',

    'home.partners.label':     'Güvenilir İş Ortaklarımız',

    'home.sub.label':          'Özel Üyelik',
    'home.sub.heading':        'Abonelik Planları',
    'home.sub.intro':          'Tüm içeriklere, eksiksiz arşive ve premium deneyimlere erişin.',
    'home.plan.popular':       'En Popüler',
    'home.plan.btn.start':     'Başla',
    'home.plan.btn.get':       'Hemen Al',

    /* ── HABERLER ── */
    'news.page.title':         'Haberler & Trendler',
    'news.cover.kicker':       'Haziran 2026 · Yaz Özel Sayısı',
    'news.cover.title':        'Moda,<br>Güzellik<br><em>& Yaşam</em>',
    'news.cover.desc':         'Yaz enerjisiyle şekillenen 2026 sezonunda podyumdan cilt bakımına, yavaş yaşamdan yıldızların rehberliğine — Fashiontv Magazine\'in Haziran editöryal seçkileri burada.',
    'news.cover.btn.primary':  'Öne Çıkanları Gör',
    'news.cover.btn.ghost':    'Tüm İçerikler',
    'news.spotlight.label':    'Bu Haftanın Seçkileri',
    'news.spotlight.heading':  'Öne Çıkan İçerikler',
    'news.spotlight.all':      'Tümünü Gör →',
    'news.read.link':          'Yazıyı Oku →',
    'news.read.more':          'Devamını Oku',
    'news.filter.all':         'Tümü',
    'news.filter.fashion':     'Moda',
    'news.filter.beauty':      'Güzellik',
    'news.filter.wellness':    'Wellness',
    'news.filter.life':        'Yaşam',
    'news.filter.astro':       'Astroloji',
    'news.filter.interview':   'Röportaj',
    'news.load.more':          'Daha Fazla İçerik Yükle',
    'news.sb.search':          'Ara',
    'news.sb.popular':         'Popüler Yazılar',
    'news.sb.cats':            'Kategoriler',
    'news.sb.edpick':          'Editörün Seçkileri',
    'news.sb.newsletter':      'Bülten',
    'news.sb.newsletter.title':'Trendlerden<br><em>Haberdar Ol</em>',
    'news.sb.newsletter.desc': 'Haftalık moda, güzellik, wellness ve yaşam içerikleri doğrudan gelen kutunuza gelsin.',
    'news.sb.newsletter.ph':   'E-posta adresiniz',
    'news.sb.newsletter.btn':  'Abone Ol',
    'news.sb.search.ph':       'İçerik ara…',

    /* ── HAKKIMIZDA ── */
    'about.hero.label':        'Biz Kimiz · 2010\'dan Bu Yana',
    'about.hero.title':        'Modanın<br>Editöryal<br><span>Sesi</span>',
    'about.hero.desc':         'Fashiontv Magazine, 2010 yılından bu yana moda, güzellik ve yaşam sanatının kesiştiği premium editöryal bir platform olarak Türkiye\'nin en seçkin okurlarına ulaşmaya devam etmektedir.',
    'about.stat1.label':       'Yıllık Deneyim',
    'about.stat2.label':       'Aylık Okuyucu',
    'about.stat3.label':       'Editöryal Sayfa',
    'about.stat4.label':       'Özel Röportaj',

    'about.story.label':       'Hikayemiz',
    'about.story.title':       'Modayı Bir <span>Sanat</span> Olarak Yorumluyoruz',
    'about.story.p1':          'Bir dergi yalnızca sayfa değildir; bir bakış açısı, bir ses, bir manifestodur. Fashiontv Magazine, modayı yüzeysel bir estetik olarak değil, kültürün, kimliğin ve yaratıcılığın derin bir yansıması olarak ele alır.',
    'about.story.p2':          'Her sayımızda Türkiye\'nin ve dünyanın en yaratıcı isimlerine yer veriyor, okurlarımıza yalnızca trendleri değil, trendlerin arkasındaki hikâyeleri ve vizyonları sunuyoruz.',
    'about.story.p3':          '2010\'dan bu yana Türkiye\'nin önde gelen tasarımcılarını, fotoğrafçılarını ve moda yazarlarını bir araya getirerek modaya gerçek anlamda premium bir ses kazandırmaya devam ediyoruz.',

    'about.mv.label':          'İlkelerimiz',
    'about.mv.title':          'Misyon &amp; <span>Vizyon</span>',
    'about.mission.tag':       'Misyonumuz',
    'about.mission.title':     'Moda Kültürünü Demokratize Etmek',
    'about.mission.text':      'Türkiye\'deki moda, güzellik ve yaşam kültürünü uluslararası editöryal standartlarla buluşturarak okurlarımıza hem ilham veren hem de bilgilendiren premium içerikler üretmek.',
    'about.vision.tag':        'Vizyonumuz',
    'about.vision.title':      'Türkiye\'nin En Prestijli Moda Platformu',
    'about.vision.text':       '2030 yılına kadar Türkiye\'nin en çok okunan ve en prestijli dijital moda yayını haline gelmek; Türk modası ve tasarımını küresel platformlarda temsil eden bir marka olmak.',

    'about.why.label':         'Farkımız',
    'about.why.title':         'Neden <span>fashiontv magazine?</span>',
    'about.why1.title':        'Bağımsız Editöryal Kimlik',
    'about.why1.text':         'İçeriklerimiz hiçbir reklam ajansının veya markanın direktifine tabi değildir. Editöryal kararlarımızı yalnızca okurlarımızın ilgi ve ihtiyaçları doğrultusunda alırız.',
    'about.why2.title':        'Uzman Kadro & Yaratıcı Ağ',
    'about.why2.text':         'Türkiye\'nin ve Avrupa\'nın en deneyimli moda editörleri, fotoğrafçıları ve stilistlerinden oluşan yaratıcı ağımızla her sayıda sektörün kalbinden içerikler üretiyoruz.',
    'about.why3.title':        'Dijital & Basılı Deneyim',
    'about.why3.text':         'Hem premium basılı dergimiz hem de zengin dijital platformumuzla okurlarımıza kesintisiz bir moda deneyimi sunuyoruz.',

    'about.values.label':      'Temel Değerlerimiz',
    'about.values.title':      'Her İçeriğin Arkasında',
    'about.value1.title':      'Güvenilirlik',
    'about.value1.text':       'Söylediklerimizin arkında duruyoruz.',
    'about.value2.title':      'Mükemmellik',
    'about.value2.text':       'Her detayda en yüksek kaliteyi arıyoruz.',
    'about.value3.title':      'Küresel Perspektif',
    'about.value3.text':       'Dünyayı ve Türkiye\'yi birlikte görüyoruz.',
    'about.value4.title':      'Yaratıcılık',
    'about.value4.text':       'Kalıpları sorguluyor, yeni perspektifler yaratıyoruz.',

    'about.cta.label':         'Bize Katılın',
    'about.cta.title':         'Premium Dünyada <span>Yerinizi Alın</span>',
    'about.cta.desc':          'Editöryal içeriklerimize, özel etkinliklerimize ve ayrıcalıklı deneyimlerimize erişmek için hemen abone olun.',
    'about.cta.btn.primary':   'Abonelik Planları',
    'about.cta.btn.ghost':     'İletişime Geç',

    /* ── İLETİŞİM ── */
    'contact.hero.label':      'Bizimle İletişime Geçin',
    'contact.hero.title':      'Sizi<br><span>Duymak</span><br>İstiyoruz',
    'contact.hero.desc':       'Reklam, iş birliği, içerik önerileri veya abonelik konularında bize ulaşabilirsiniz. Ekibimiz en kısa sürede size geri dönecektir.',
    'contact.info.label':      'İletişim Bilgileri',
    'contact.info.title':      'Bize Ulaşın',
    'contact.info.intro':      'Hafta içi 09:00–18:00 saatleri arasında tüm kanallardan bize ulaşabilirsiniz.',
    'contact.detail.address':  'Adres',
    'contact.detail.email':    'E-posta',
    'contact.detail.phone':    'Telefon',
    'contact.detail.hours':    'Çalışma Saatleri',
    'contact.social.label':    'Sosyal Medya',
    'contact.form.label':      'Mesaj Gönderin',
    'contact.form.title':      'Formdan Yazın',
    'contact.field.firstname': 'Adınız',
    'contact.field.lastname':  'Soyadınız',
    'contact.field.email':     'E-posta Adresi',
    'contact.field.subject':   'Konu',
    'contact.field.message':   'Mesajınız',
    'contact.subject.select':  'Bir konu seçin',
    'contact.subject.ads':     'Reklam & İş Birliği',
    'contact.subject.sub':     'Abonelik',
    'contact.subject.content': 'İçerik Önerisi',
    'contact.subject.tech':    'Teknik Destek',
    'contact.subject.other':   'Diğer',
    'contact.ph.firstname':    'Adınız',
    'contact.ph.lastname':     'Soyadınız',
    'contact.ph.email':        'ornek@email.com',
    'contact.ph.message':      'Mesajınızı buraya yazın…',
    'contact.submit':          'Mesajı Gönder',
    'contact.faq.label':       'Soru & Cevap',
    'contact.faq.title':       'Sıkça Sorulan Sorular',

    /* ── ABONELİK ── */
    'sub.hero.label':          'Özel Üyelik Planları',
    'sub.hero.title':          'Premium<br><span>Abonelik</span>',
    'sub.hero.desc':           'Fashiontv Magazine\'in tüm içeriklerine, özel editoriallerine ve ayrıcalıklı deneyimlerine sınırsız erişim sağlayın.',
    'sub.badge.secure':        'Güvenli Ödeme',
    'sub.badge.cancel':        'İstediğiniz Zaman İptal',
    'sub.badge.instant':       'Anında Erişim',
    'sub.badge.premium':       'Premium İçerik',
    'sub.benefit1':            'Dijital + Basılı Dergi',
    'sub.benefit2':            'Tam Arşiv Erişimi',
    'sub.benefit3':            'Özel Etkinlik Davetleri',
    'sub.benefit4':            'Dergi Tasarım Aracı',
    'sub.benefit5':            'Öncelikli Destek',
    'sub.plans.label':         'Üyelik Seçenekleri',
    'sub.plans.title':         'Size Uygun <span>Planı Seçin</span>',
    'sub.plans.sub':           'Uzun vadeli planlar daha fazla tasarruf sağlar. İstediğiniz zaman iptal edebilirsiniz.',
    'sub.plan.popular':        'En Popüler',
    'sub.plan.select':         'Planı Seç',
    'sub.plan.featured.btn':   'Hemen Al',
    'sub.cta.title':           'Bugün Başlayın,<br><span>Farkı Hissedin</span>',
    'sub.cta.desc':            'Premium editoryal içerikler, özel etkinlikler ve ayrıcalıklı deneyimler sizi bekliyor.',
    'sub.cta.btn.primary':     'Plan Seç',
    'sub.cta.btn.ghost':       'Önce İçerikleri İncele',
    'sub.faq.label':           'Soru & Cevap',
    'sub.faq.title':           'Sıkça Sorulan Sorular',

    /* ── GİRİŞ ── */
    'login.back':              'Ana Sayfa',
    'login.kicker':            'Üye Girişi · 2026',
    'login.heading':           'Lüks &amp; Stil<br><em>Dünyasına</em><br>Geri Dönün',
    'login.text':              'Podyumdan yaşam sanatına, editöryal içeriklerden özel etkinliklere — premium dünyaya hoş geldiniz.',
    'login.form.label':        'Üye Girişi',
    'login.form.title':        'Giriş Yap',
    'login.form.sub':          'Hesabınız yok mu?',
    'login.form.sub.link':     'Hemen kayıt olun',
    'login.field.email':       'E-posta Adresi',
    'login.field.password':    'Şifre',
    'login.ph.email':          'ornek@email.com',
    'login.ph.password':       'Şifrenizi giriniz',
    'login.forgot':            'Şifremi unuttum',
    'login.btn':               'Giriş Yap',
    'login.or':                'veya',
    'login.new.account':       'Yeni Hesap Oluştur',
    'login.security':          '256-bit SSL korumalı güvenli bağlantı',

    /* ── KAYIT ── */
    'register.kicker':         'Yeni Üyelik · 2026',
    'register.heading':        'Premium<br><em>Dünyaya</em><br>Katılın',
    'register.text':           'Editöryal içerikler, özel etkinlikler ve ayrıcalıklı deneyimler — hepsi tek üyelikte.',
    'register.form.label':     'Yeni Üyelik',
    'register.form.title':     'Hesap Oluştur',
    'register.form.sub':       'Zaten hesabınız var mı?',
    'register.form.sub.link':  'Giriş yapın',
    'register.field.firstname':'Adınız',
    'register.field.lastname': 'Soyadınız',
    'register.field.email':    'E-posta Adresi',
    'register.field.password': 'Şifre',
    'register.field.confirm':  'Şifre Tekrar',
    'register.ph.firstname':   'Adınız',
    'register.ph.lastname':    'Soyadınız',
    'register.ph.email':       'ornek@email.com',
    'register.ph.password':    'En az 6 karakter',
    'register.ph.confirm':     'Şifrenizi tekrar giriniz',
    'register.kvkk':           '\'nı ve',
    'register.kvkk.terms':     'Kullanım Koşulları',
    'register.kvkk.privacy':   'Gizlilik Politikası',
    'register.kvkk.suffix':    '\'nı (KVKK) okudum, kabul ediyorum.',
    'register.btn':            'Hesap Oluştur',
    'register.security':       'SSL ile korunan güvenli bağlantı · Bilgileriniz şifrelenmiş saklanır',

    /* ── HESABIM ── */
    'account.logout':          'Çıkış Yap',

    /* ── YASAL SAYFALAR ── */
    'legal.kicker':            'Yasal',
    'privacy.title':           'Gizlilik Politikası',
    'terms.title':             'Kullanım Koşulları',
    'cookie.title':            'Çerez Politikası',

    /* ── ŞİFREMİ UNUTTUM ── */
    'forgot.nav.home':         'Ana Sayfa',
    'forgot.nav.news':         'Haberler',
    'forgot.nav.sub':          'Abonelik',

    /* ── HABER SAYFASI (nav/footer sadece) ── */
    'article.back':            'Haberlere Dön',

    /* ── HABERLER SAYFASI EK ── */
    'news.tape.date':          'Haziran 2026',
    'news.tape.pick':          'Editörün Seçimi',
    'news.tape.cats':          'Moda · Güzellik · Wellness · Yaşam · Astroloji · Röportaj',
    'news.cat.count.fashion':  '12 yazı',
    'news.cat.count.beauty':   '10 yazı',
    'news.cat.count.wellness': '9 yazı',
    'news.cat.count.life':     '8 yazı',
    'news.cat.count.astro':    '8 yazı',
    'news.cat.count.interview':'5 yazı',
    'news.editor.label':       'Editörün Seçkisi',
    'news.cover.date':         '12 Haziran 2026',
    'news.cover.vol':          'Haziran Sayısı · Vol. 27',

    /* ── HABERLER MAKALELERİ ── */
    'news.art.moda1.title':     '2026 Yaz Sezonu: Minimalizmin Güçlü Geri Dönüşü',
    'news.art.moda1.excerpt':   'Milano, Paris ve Kopenhag podyumlarında bu sezonun ortak dili: net çizgiler, premium kumaşlar ve zamansız sadelik manifestosu.',
    'news.art.guzellik1.title': 'Glazed Skin Rutini: Yazın Işıltılı Cilt Görünümü',
    'news.art.guzellik1.excerpt':'Hyaluronik asit, seramid ve peptid ile yazın en çok konuşulan doğal parlaklık trendi.',
    'news.art.wellness1.title': 'Yavaş Yaşamın Yükselişi: 2026\'nın Yeni Lüks Anlayışı',
    'news.art.wellness1.excerpt':'Slow living yaklaşımı 2026 wellness dünyasının merkezine oturdu. Zihinsel huzur yeni lüks.',
    'news.art.yasam1.title':    'Cilt Bakımının Yeni Altın Kuralı: Az Ürün, Daha Fazla Etki',
    'news.art.yasam1.excerpt':  'Dermatologlara göre doğru ürün seçimi, uzun ve karmaşık bakım rutinlerinden çok daha etkili.',
    'news.art.astro1.title':    'Haziran Burç Yorumları: Yaz Enerjisi Başlıyor',
    'news.art.astro1.excerpt':  'Venüs ve Mars etkileriyle Haziran 2026\'da güçlü başlangıç enerjileri tüm burçlara yansıyor.',
    'news.art.roportaj1.title': 'Serra Kaya ile Özel Söyleşi',
    'news.art.roportaj1.excerpt':'Modanın güçlü ismi Serra Kaya, stil felsefesini, ilham kaynaklarını ve moda dünyasındaki yolculuğunu anlattı.',
    'news.art.moda2.title':     'Valentino\'nun Yeni Vizyonu: Lükste Sanatsal Anlatının Dönüşümü',
    'news.art.moda2.excerpt':   'Yeni yaratıcı direktörün koleksiyonu, moda dünyasında köklü bir kırılmaya işaret ediyor.',
    'news.art.guzellik2.title': 'Nişan Makyajında Klasik ile Modernin Buluşma Noktası',
    'news.art.guzellik2.excerpt':'Düğün sezonu için en çok tercih edilen makyaj stilleri ve ürünler üzerine kapsamlı bir rehber.',
    'news.art.wellness2.title': 'Bitkisel Uyku Rutini: Derin ve Kaliteli Uyku İçin 7 Adım',
    'news.art.wellness2.excerpt':'Uyku kalitesini artıran doğal yöntemler ve uzman önerileriyle gece rutininizi dönüştürün.',
    'news.art.yasam2.title':    'Yavaş Seyahat Lüks mü? Moda Editörlerinin Yeni Keşif Biçimi',
    'news.art.yasam2.excerpt':  'Koşturmacalı turların yerini alan derin, anlamlı yolculuklar artık yeni prestij simgesi.',
    'news.art.astro2.title':    'Temmuz Burç Yorumları: Dönüşüm Zamanı',
    'news.art.astro2.excerpt':  'Jüpiter\'in etkisiyle Temmuz 2026\'da büyük değişimler kapıda.',
    'news.art.roportaj2.title': 'Tasarımcı Bora Aksu ile Moda, Kimlik ve İstanbul Üzerine',
    'news.art.roportaj2.excerpt':'Londra podyumlarını fetheden Türk tasarımcı, kültürel köklerin moda diline nasıl dönüştüğünü anlattı.',

    /* ── SPOTLIGHT KARTLARI ── */
    'news.spotlight.moda.title':    'Yaz Sezonunda Capsule Wardrobe: 10 Parça ile Güçlü Stil',
    'news.spotlight.wellness.title':'Sabah Rutinini Değiştiren 6 Küçük Alışkanlık',

    /* ── EDİTÖR ŞERİDİ ── */
    'news.editor.link1':        '2026 Moda Trendleri',
    'news.editor.link2':        'Cilt Bakım Rutini',
    'news.editor.link3':        'Haziran Burç Yorumları',
    'news.editor.link4':        'Minimalist Yaşam',
    'news.editor.link5':        'Özel Röportajlar',

    /* ── ABONELİK SAYFASI EK ── */
    'sub.hero.desc':           'Fashiontv Magazine\'in tüm içeriklerine, özel editoriallerine ve ayrıcalıklı deneyimlerine sınırsız erişim sağlayın.',
    'sub.plans.sub':           'Uzun vadeli planlar daha fazla tasarruf sağlar. İstediğiniz zaman iptal edebilirsiniz.',
    'sub.period.3m':           '3 Aylık',
    'sub.period.6m':           '6 Aylık',
    'sub.period.9m':           '9 Aylık',
    'sub.period.1y':           '1 Yıllık',
    'sub.period.3y':           '3 Yıllık',
    'sub.period.5y':           '5 Yıllık',
    'sub.cycle.3m':            '/ 3 ay',
    'sub.cycle.6m':            '/ 6 ay',
    'sub.cycle.9m':            '/ 9 ay',
    'sub.cycle.1y':            '/ yıl',
    'sub.cycle.3y':            '/ 3 yıl',
    'sub.cycle.5y':            '/ 5 yıl',
    'sub.saving.16':           '%16 İndirim',
    'sub.saving.22':           '%22 İndirim',
    'sub.saving.29':           '%29 İndirim',
    'sub.saving.34':           '%34 İndirim',
    'sub.saving.40':           '%40 İndirim',
    'sub.feat.digital':        'Dijital Erişim',
    'sub.feat.archive.3m':     '3 Aylık Arşiv',
    'sub.feat.newsletter':     'Haftalık Bülten',
    'sub.feat.digital_print':  'Dijital + Basılı Dergi',
    'sub.feat.archive.6m':     '6 Aylık Arşiv',
    'sub.feat.events':         'Özel Etkinlik Davetleri',
    'sub.feat.archive.9m':     '9 Aylık Arşiv',
    'sub.feat.design_tool':    'Dergi Tasarım Aracı',
    'sub.feat.full_archive':   'Tam Arşiv Erişimi',
    'sub.feat.priority':       'Öncelikli Müşteri Desteği',
    'sub.feat.all_premium':    'Tüm Premium Avantajlar',
    'sub.feat.cover_gift':     'Özel Kapak Hediyesi',
    'sub.feat.vip_events':     'VIP Etkinlik Erişimi',
    'sub.feat.style_advisor':  'Kişisel Stil Danışmanı',
    'sub.feat.all_elite':      'Tüm Elite Avantajlar',
    'sub.feat.print_col':      'Özel Baskı Koleksiyonu',
    'sub.feat.workshop':       'Atölye & Masterclass',
    'sub.feat.brand_partner':  'Brand Partnership',
    'sub.feat.welcome_kit':    'Lüks Hoşgeldin Kiti',
    'sub.cta.desc':            'Premium editoryal içerikler, özel etkinlikler ve ayrıcalıklı deneyimler sizi bekliyor.',
    'sub.faq.q1': 'Aboneliğimi istediğim zaman iptal edebilir miyim?',
    'sub.faq.a1': 'Evet. Aboneliğinizi hesabınız üzerinden herhangi bir zamanda iptal edebilirsiniz. İptal, mevcut dönem sona erdiğinde yürürlüğe girer; bu süre zarfında tüm avantajlarınıza erişmeye devam edersiniz.',
    'sub.faq.q2': 'Hangi ödeme yöntemlerini kabul ediyorsunuz?',
    'sub.faq.a2': 'Visa, Mastercard ve American Express kredi/banka kartları ile ödeme yapabilirsiniz. Tüm işlemler 256-bit SSL şifreli güvenli altyapı üzerinden gerçekleştirilir.',
    'sub.faq.q3': 'Dijital içeriklere ne zaman erişebilirim?',
    'sub.faq.a3': 'Ödemeniz onaylandıktan sonra dijital içeriklere anında erişim sağlanır. Basılı dergi ise kayıtlı adresinize birkaç iş günü içinde ulaşır.',
    'sub.faq.q4': 'Planımı daha sonra yükseltebilir miyim?',
    'sub.faq.a4': 'Mevcut abonelik döneminiz tamamlandığında dilediğiniz plana geçiş yapabilirsiniz. Erken geçiş için müşteri hizmetlerimizle iletişime geçebilirsiniz.',
    'sub.faq.q5': 'Dergi Tasarım Aracı hangi planlarda yer alıyor?',
    'sub.faq.a5': 'Dergi Tasarım Aracı, Classic planından itibaren tüm üst planlarda (Classic, Premium, Elite, Maison) aktif olarak kullanılabilmektedir.',
  },

  /* ─────────────────── ENGLISH ─────────────────── */
  en: {
    'nav.home':       'Home',
    'nav.news':       'News',
    'nav.about':      'About Us',
    'nav.sub':        'Subscription',
    'nav.contact':    'Contact',
    'nav.login':      'Sign In',
    'nav.logout':     'Sign Out',
    'nav.account':    'My Account',

    'footer.tagline':       'The premium editorial platform where fashion, beauty and the art of living meet.',
    'footer.col.discover':  'Discover',
    'footer.col.corporate': 'Corporate',
    'footer.col.membership':'Membership',
    'footer.issue':         'This Month\'s Issue',
    'footer.fashion':       'Fashion',
    'footer.beauty':        'Beauty',
    'footer.life':          'Lifestyle',
    'footer.trends':        'Trends',
    'footer.interviews':    'Exclusive Interviews',
    'footer.about':         'About Us',
    'footer.ads':           'Advertising & Media',
    'footer.career':        'Career',
    'footer.contact':       'Contact',
    'footer.press':         'Press',
    'footer.plans':         'Plans',
    'footer.gift':          'Gift Subscription',
    'footer.archive':       'Digital Archive',
    'footer.design':        'Design a Magazine',
    'footer.support':       'Support',
    'footer.copy':          '© 2026 Fashiontv Magazine. All rights reserved.',
    'footer.privacy':       'Privacy Policy',
    'footer.terms':         'Terms of Use',
    'footer.cookie':        'Cookie Policy',

    'home.hero.label':         'fashiontv magazine',
    'home.hero.title':         'Fashion, Beauty<br><em>& The Art of Living</em>',
    'home.hero.sub':           'From the runway to life — the premium magazine where luxury meets style.',
    'home.hero.btn.issue':     'This Month\'s Issue',
    'home.hero.btn.sub':       'Subscribe',

    'home.editorial.label':    'Fashiontv Magazine',
    'home.editorial.title':    'Don\'t just follow fashion,<br>be part of it',
    'home.editorial.text':     'Fashiontv Magazine offers a distinguished editorial experience that brings together fashion, beauty, culture and lifestyle. Every issue is crafted with inspiring visuals, powerful stories and timeless aesthetics.',
    'home.editorial.feat1':    'Exclusive editorial content',
    'home.editorial.feat2':    'Premium magazine experience',
    'home.editorial.feat3':    'Digital & creative design platform',
    'home.editorial.btn.dark': 'This Month\'s Issue',
    'home.editorial.btn.sub':  'Explore Subscription',

    'home.issue.label':        'Current Issue',
    'home.issue.heading':      'fashiontv magazine <br><em>April Issue Out Now</em>',
    'home.issue.body':         'This month\'s special issue features exclusive interviews with the world\'s most prestigious names, an in-depth analysis of the Spring–Summer 2026 collections, and visionary designers shaping the future of fashion.',
    'home.issue.li1':          '12 In-Depth Interviews',
    'home.issue.li2':          '40+ Pages of Special Editorial',
    'home.issue.li3':          'Collection Analysis & Trends',
    'home.issue.btn':          'Subscribe Now',

    'home.cats.label':         'Discover',
    'home.cats.heading':       'Categories',
    'home.cat1.name':          'Fashion',
    'home.cat1.desc':          'Collections & style guides',
    'home.cat2.name':          'Beauty',
    'home.cat2.desc':          'Beauty editorials',
    'home.cat3.name':          'Lifestyle',
    'home.cat3.desc':          'Luxury living & culture',
    'home.cat4.name':          'Trends',
    'home.cat4.desc':          'The season\'s direction',
    'home.cat5.name':          'Exclusive Interviews',
    'home.cat5.desc':          'Icons of fashion',

    'home.casting.eyebrow':    'fashiontv magazine casting',
    'home.casting.title':      'Want to be a Model, Mannequin<br>or Actor?',
    'home.casting.desc':       'Create your application, let our team review it. Once approved, your listing reaches thousands of professionals — for free.',
    'home.casting.btn.apply':  'Apply Now',
    'home.casting.btn.browse': 'Explore Casting',

    'home.featured.label':     'Featured',
    'home.featured.heading':   'Editor\'s Choice',
    'home.featured.all':       'See All →',
    'home.read.more':          'Read More',

    'home.design.label':       'Creative Tool',
    'home.design.heading':     'You\'re Our Cover Star!<br /><em>Ready for the Interview?</em>',
    'home.design.body':        'Create your own editorial cover with Fashiontv Magazine\'s powerful design platform. Professional templates, corporate brand kit and print-ready output await you.',
    'home.design.feat1':       '50+ Premium Templates',
    'home.design.feat2':       'Corporate Brand Kit',
    'home.design.feat3':       'Print-Ready 300 DPI Output',
    'home.design.btn':         'Start Designing',

    'home.partners.label':     'Our Trusted Partners',

    'home.sub.label':          'Exclusive Membership',
    'home.sub.heading':        'Subscription Plans',
    'home.sub.intro':          'Access all content, complete archives and premium experiences.',
    'home.plan.popular':       'Most Popular',
    'home.plan.btn.start':     'Get Started',
    'home.plan.btn.get':       'Get Now',

    'news.page.title':         'News & Trends',
    'news.cover.kicker':       'June 2026 · Summer Special',
    'news.cover.title':        'Fashion,<br>Beauty<br><em>& Life</em>',
    'news.cover.desc':         'The 2026 season shaped by summer energy — from the runway to skincare, from slow living to the stars\' guidance — Fashiontv Magazine\'s June editorial picks are here.',
    'news.cover.btn.primary':  'See Highlights',
    'news.cover.btn.ghost':    'All Content',
    'news.spotlight.label':    'This Week\'s Picks',
    'news.spotlight.heading':  'Featured Content',
    'news.spotlight.all':      'See All →',
    'news.read.link':          'Read Article →',
    'news.read.more':          'Read More',
    'news.filter.all':         'All',
    'news.filter.fashion':     'Fashion',
    'news.filter.beauty':      'Beauty',
    'news.filter.wellness':    'Wellness',
    'news.filter.life':        'Lifestyle',
    'news.filter.astro':       'Astrology',
    'news.filter.interview':   'Interview',
    'news.load.more':          'Load More Content',
    'news.sb.search':          'Search',
    'news.sb.popular':         'Popular Articles',
    'news.sb.cats':            'Categories',
    'news.sb.edpick':          'Editor\'s Picks',
    'news.sb.newsletter':      'Newsletter',
    'news.sb.newsletter.title':'Stay Ahead<br><em>of Trends</em>',
    'news.sb.newsletter.desc': 'Weekly fashion, beauty, wellness and lifestyle content delivered straight to your inbox.',
    'news.sb.newsletter.ph':   'Your email address',
    'news.sb.newsletter.btn':  'Subscribe',
    'news.sb.search.ph':       'Search content…',

    'about.hero.label':        'Who We Are · Since 2010',
    'about.hero.title':        'The Editorial<br>Voice of<br><span>Fashion</span>',
    'about.hero.desc':         'Since 2010, Fashiontv Magazine has been reaching Turkey\'s most discerning readers as a premium editorial platform at the intersection of fashion, beauty and the art of living.',
    'about.stat1.label':       'Years of Experience',
    'about.stat2.label':       'Monthly Readers',
    'about.stat3.label':       'Editorial Pages',
    'about.stat4.label':       'Exclusive Interviews',

    'about.story.label':       'Our Story',
    'about.story.title':       'We Interpret Fashion as <span>Art</span>',
    'about.story.p1':          'A magazine is not merely pages; it is a perspective, a voice, a manifesto. Fashiontv Magazine treats fashion not as a superficial aesthetic, but as a deep reflection of culture, identity and creativity.',
    'about.story.p2':          'Every issue features Turkey\'s and the world\'s most creative voices, offering our readers not just trends, but the stories and visions behind them.',
    'about.story.p3':          'Since 2010, we have brought together Turkey\'s leading designers, photographers and fashion writers, giving fashion a truly premium voice.',

    'about.mv.label':          'Our Principles',
    'about.mv.title':          'Mission &amp; <span>Vision</span>',
    'about.mission.tag':       'Our Mission',
    'about.mission.title':     'Democratizing Fashion Culture',
    'about.mission.text':      'Producing premium content that both inspires and informs our readers by bringing together Turkey\'s fashion, beauty and lifestyle culture with international editorial standards.',
    'about.vision.tag':        'Our Vision',
    'about.vision.title':      'Turkey\'s Most Prestigious Fashion Platform',
    'about.vision.text':       'To become Turkey\'s most-read and most prestigious digital fashion publication by 2030; to be a brand that represents Turkish fashion and design on global platforms.',

    'about.why.label':         'Our Difference',
    'about.why.title':         'Why <span>fashiontv magazine?</span>',
    'about.why1.title':        'Independent Editorial Identity',
    'about.why1.text':         'Our content is not subject to directives from any advertising agency or brand. We make editorial decisions solely in line with our readers\' interests and needs.',
    'about.why2.title':        'Expert Team & Creative Network',
    'about.why2.text':         'We produce content from the heart of the industry with our extensive creative network of Turkey\'s and Europe\'s most experienced fashion editors, photographers and stylists.',
    'about.why3.title':        'Digital & Print Experience',
    'about.why3.text':         'We offer our readers a seamless fashion experience through both our premium print magazine and our rich digital platform.',

    'about.values.label':      'Our Core Values',
    'about.values.title':      'Behind Every Piece of Content',
    'about.value1.title':      'Reliability',
    'about.value1.text':       'We stand behind everything we say.',
    'about.value2.title':      'Excellence',
    'about.value2.text':       'We seek the highest quality in every detail.',
    'about.value3.title':      'Global Perspective',
    'about.value3.text':       'We see the world and Turkey together.',
    'about.value4.title':      'Creativity',
    'about.value4.text':       'We question norms and create new perspectives.',

    'about.cta.label':         'Join Us',
    'about.cta.title':         'Claim Your Place in <span>the Premium World</span>',
    'about.cta.desc':          'Subscribe now to access our editorial content, exclusive events and privileged experiences.',
    'about.cta.btn.primary':   'Subscription Plans',
    'about.cta.btn.ghost':     'Get in Touch',

    'contact.hero.label':      'Get in Touch with Us',
    'contact.hero.title':      'We Want<br>to <span>Hear</span><br>You',
    'contact.hero.desc':       'You can reach us for advertising, collaboration, content suggestions or subscription matters. Our team will get back to you as soon as possible.',
    'contact.info.label':      'Contact Information',
    'contact.info.title':      'Reach Us',
    'contact.info.intro':      'You can reach us through all channels on weekdays between 09:00–18:00.',
    'contact.detail.address':  'Address',
    'contact.detail.email':    'Email',
    'contact.detail.phone':    'Phone',
    'contact.detail.hours':    'Working Hours',
    'contact.social.label':    'Social Media',
    'contact.form.label':      'Send a Message',
    'contact.form.title':      'Write via Form',
    'contact.field.firstname': 'First Name',
    'contact.field.lastname':  'Last Name',
    'contact.field.email':     'Email Address',
    'contact.field.subject':   'Subject',
    'contact.field.message':   'Your Message',
    'contact.subject.select':  'Select a subject',
    'contact.subject.ads':     'Advertising & Collaboration',
    'contact.subject.sub':     'Subscription',
    'contact.subject.content': 'Content Suggestion',
    'contact.subject.tech':    'Technical Support',
    'contact.subject.other':   'Other',
    'contact.ph.firstname':    'Your first name',
    'contact.ph.lastname':     'Your last name',
    'contact.ph.email':        'example@email.com',
    'contact.ph.message':      'Write your message here…',
    'contact.submit':          'Send Message',
    'contact.faq.label':       'Q & A',
    'contact.faq.title':       'Frequently Asked Questions',

    'sub.hero.label':          'Exclusive Membership Plans',
    'sub.hero.title':          'Premium<br><span>Subscription</span>',
    'sub.hero.desc':           'Unlock unlimited access to all Fashiontv Magazine content, exclusive editorials and privileged experiences.',
    'sub.badge.secure':        'Secure Payment',
    'sub.badge.cancel':        'Cancel Anytime',
    'sub.badge.instant':       'Instant Access',
    'sub.badge.premium':       'Premium Content',
    'sub.benefit1':            'Digital + Print Magazine',
    'sub.benefit2':            'Full Archive Access',
    'sub.benefit3':            'Exclusive Event Invitations',
    'sub.benefit4':            'Magazine Design Tool',
    'sub.benefit5':            'Priority Support',
    'sub.plans.label':         'Membership Options',
    'sub.plans.title':         'Choose the <span>Plan for You</span>',
    'sub.plans.sub':           'Long-term plans save more. Cancel anytime.',
    'sub.plan.popular':        'Most Popular',
    'sub.plan.select':         'Choose Plan',
    'sub.plan.featured.btn':   'Get Now',
    'sub.cta.title':           'Start Today,<br><span>Feel the Difference</span>',
    'sub.cta.desc':            'Premium editorial content, exclusive events and privileged experiences await you.',
    'sub.cta.btn.primary':     'Choose a Plan',
    'sub.cta.btn.ghost':       'Browse Content First',
    'sub.faq.label':           'Q & A',
    'sub.faq.title':           'Frequently Asked Questions',

    'login.back':              'Home',
    'login.kicker':            'Member Login · 2026',
    'login.heading':           'Welcome Back to<br>the World of<br><em>Luxury & Style</em>',
    'login.text':              'From the runway to the art of living, from editorial content to exclusive events — welcome to the premium world.',
    'login.form.label':        'Member Login',
    'login.form.title':        'Sign In',
    'login.form.sub':          'Don\'t have an account?',
    'login.form.sub.link':     'Register now',
    'login.field.email':       'Email Address',
    'login.field.password':    'Password',
    'login.ph.email':          'example@email.com',
    'login.ph.password':       'Enter your password',
    'login.forgot':            'Forgot password',
    'login.btn':               'Sign In',
    'login.or':                'or',
    'login.new.account':       'Create New Account',
    'login.security':          'Secure connection with 256-bit SSL',

    'register.kicker':         'New Membership · 2026',
    'register.heading':        'Join the<br><em>Premium</em><br>World',
    'register.text':           'Editorial content, exclusive events and privileged experiences — all in one membership.',
    'register.form.label':     'New Membership',
    'register.form.title':     'Create Account',
    'register.form.sub':       'Already have an account?',
    'register.form.sub.link':  'Sign in',
    'register.field.firstname':'First Name',
    'register.field.lastname': 'Last Name',
    'register.field.email':    'Email Address',
    'register.field.password': 'Password',
    'register.field.confirm':  'Confirm Password',
    'register.ph.firstname':   'Your first name',
    'register.ph.lastname':    'Your last name',
    'register.ph.email':       'example@email.com',
    'register.ph.password':    'At least 6 characters',
    'register.ph.confirm':     'Re-enter your password',
    'register.kvkk.terms':     'Terms of Use',
    'register.kvkk.privacy':   'Privacy Policy',
    'register.btn':            'Create Account',
    'register.security':       'Secure connection with SSL · Your information is stored encrypted',

    'account.logout':          'Sign Out',

    'legal.kicker':            'Legal',
    'privacy.title':           'Privacy Policy',
    'terms.title':             'Terms of Use',
    'cookie.title':            'Cookie Policy',

    'forgot.nav.home':         'Home',
    'forgot.nav.news':         'News',
    'forgot.nav.sub':          'Subscription',

    'article.back':            'Back to News',

    'news.tape.date':          'June 2026',
    'news.tape.pick':          "Editor's Choice",
    'news.tape.cats':          'Fashion · Beauty · Wellness · Lifestyle · Astrology · Interview',
    'news.cat.count.fashion':  '12 articles',
    'news.cat.count.beauty':   '10 articles',
    'news.cat.count.wellness': '9 articles',
    'news.cat.count.life':     '8 articles',
    'news.cat.count.astro':    '8 articles',
    'news.cat.count.interview':'5 articles',
    'news.editor.label':       "Editor's Picks",
    'news.cover.date':         'June 12, 2026',
    'news.cover.vol':          'June Issue · Vol. 27',

    /* ── NEWS ARTICLES ── */
    'news.art.moda1.title':     '2026 Summer Season: The Powerful Return of Minimalism',
    'news.art.moda1.excerpt':   'The common language of this season on the runways of Milan, Paris and Copenhagen: clean lines, premium fabrics and a timeless simplicity manifesto.',
    'news.art.guzellik1.title': 'Glazed Skin Routine: Luminous Skin Look of Summer',
    'news.art.guzellik1.excerpt':'The most talked-about natural radiance trend of summer with hyaluronic acid, ceramides and peptides.',
    'news.art.wellness1.title': 'The Rise of Slow Living: The New Luxury of 2026',
    'news.art.wellness1.excerpt':'The slow living approach has taken center stage in the 2026 wellness world. Mental peace is the new luxury.',
    'news.art.yasam1.title':    'The New Golden Rule of Skincare: Less Product, More Effect',
    'news.art.yasam1.excerpt':  'According to dermatologists, choosing the right product is far more effective than long and complex skincare routines.',
    'news.art.astro1.title':    'June Horoscopes: Summer Energy Begins',
    'news.art.astro1.excerpt':  'With the influence of Venus and Mars, powerful new beginning energies are reflected in all signs in June 2026.',
    'news.art.roportaj1.title': 'Exclusive Interview with Serra Kaya',
    'news.art.roportaj1.excerpt':'The powerful name of fashion, Serra Kaya, shared her style philosophy, sources of inspiration and journey in the fashion world.',
    'news.art.moda2.title':     "Valentino's New Vision: The Transformation of Artistic Narrative in Luxury",
    'news.art.moda2.excerpt':   "The new creative director's collection signals a radical break in the fashion world.",
    'news.art.guzellik2.title': 'Where Classic Meets Modern in Engagement Makeup',
    'news.art.guzellik2.excerpt':'A comprehensive guide to the most preferred makeup styles and products for the wedding season.',
    'news.art.wellness2.title': 'Herbal Sleep Routine: 7 Steps for Deep and Quality Sleep',
    'news.art.wellness2.excerpt':'Transform your nighttime routine with natural methods and expert recommendations that improve sleep quality.',
    'news.art.yasam2.title':    "Is Slow Travel a Luxury? Fashion Editors' New Way of Exploration",
    'news.art.yasam2.excerpt':  'Deep, meaningful journeys that replace rushed tours are now the new symbol of prestige.',
    'news.art.astro2.title':    'July Horoscopes: Time for Transformation',
    'news.art.astro2.excerpt':  "With Jupiter's influence, major changes are on the horizon in July 2026.",
    'news.art.roportaj2.title': 'Designer Bora Aksu on Fashion, Identity and Istanbul',
    'news.art.roportaj2.excerpt':'The Turkish designer who conquered London\'s runways talked about how cultural roots are transformed into the language of fashion.',

    /* ── SPOTLIGHT CARDS ── */
    'news.spotlight.moda.title':    'Capsule Wardrobe for Summer: Strong Style with 10 Pieces',
    'news.spotlight.wellness.title':'6 Small Habits That Transform Your Morning Routine',

    /* ── EDITOR STRIP ── */
    'news.editor.link1':        '2026 Fashion Trends',
    'news.editor.link2':        'Skincare Routine',
    'news.editor.link3':        'June Horoscopes',
    'news.editor.link4':        'Minimalist Living',
    'news.editor.link5':        'Exclusive Interviews',

    'sub.hero.desc':           'Unlock unlimited access to all Fashiontv Magazine content, exclusive editorials and privileged experiences.',
    'sub.plans.sub':           'Long-term plans save more. Cancel anytime.',
    'sub.period.3m':           '3 Months',
    'sub.period.6m':           '6 Months',
    'sub.period.9m':           '9 Months',
    'sub.period.1y':           '1 Year',
    'sub.period.3y':           '3 Years',
    'sub.period.5y':           '5 Years',
    'sub.cycle.3m':            '/ 3 months',
    'sub.cycle.6m':            '/ 6 months',
    'sub.cycle.9m':            '/ 9 months',
    'sub.cycle.1y':            '/ year',
    'sub.cycle.3y':            '/ 3 years',
    'sub.cycle.5y':            '/ 5 years',
    'sub.saving.16':           '16% Off',
    'sub.saving.22':           '22% Off',
    'sub.saving.29':           '29% Off',
    'sub.saving.34':           '34% Off',
    'sub.saving.40':           '40% Off',
    'sub.feat.digital':        'Digital Access',
    'sub.feat.archive.3m':     '3-Month Archive',
    'sub.feat.newsletter':     'Weekly Newsletter',
    'sub.feat.digital_print':  'Digital + Print Magazine',
    'sub.feat.archive.6m':     '6-Month Archive',
    'sub.feat.events':         'Exclusive Event Invitations',
    'sub.feat.archive.9m':     '9-Month Archive',
    'sub.feat.design_tool':    'Magazine Design Tool',
    'sub.feat.full_archive':   'Full Archive Access',
    'sub.feat.priority':       'Priority Customer Support',
    'sub.feat.all_premium':    'All Premium Benefits',
    'sub.feat.cover_gift':     'Exclusive Cover Gift',
    'sub.feat.vip_events':     'VIP Event Access',
    'sub.feat.style_advisor':  'Personal Style Advisor',
    'sub.feat.all_elite':      'All Elite Benefits',
    'sub.feat.print_col':      'Exclusive Print Collection',
    'sub.feat.workshop':       'Workshop & Masterclass',
    'sub.feat.brand_partner':  'Brand Partnership',
    'sub.feat.welcome_kit':    'Luxury Welcome Kit',
    'sub.cta.desc':            'Premium editorial content, exclusive events and privileged experiences await you.',
    'sub.faq.q1': 'Can I cancel my subscription at any time?',
    'sub.faq.a1': 'Yes. You can cancel your subscription at any time through your account. Cancellation takes effect at the end of the current period; you continue to enjoy all benefits during this time.',
    'sub.faq.q2': 'Which payment methods do you accept?',
    'sub.faq.a2': 'You can pay with Visa, Mastercard and American Express credit/debit cards. All transactions are processed through a secure 256-bit SSL encrypted infrastructure.',
    'sub.faq.q3': 'When can I access digital content?',
    'sub.faq.a3': 'Digital access is granted immediately after your payment is confirmed. The print magazine will be delivered to your registered address within a few business days.',
    'sub.faq.q4': 'Can I upgrade my plan later?',
    'sub.faq.a4': 'You can switch to any plan once your current subscription period ends. For early upgrades, please contact our customer service.',
    'sub.faq.q5': 'Which plans include the Magazine Design Tool?',
    'sub.faq.a5': 'The Magazine Design Tool is available in all plans from Classic and above (Classic, Premium, Elite, Maison).',
  },

  /* ─────────────────── РУССКИЙ ─────────────────── */
  ru: {
    'nav.home':       'Главная',
    'nav.news':       'Новости',
    'nav.about':      'О нас',
    'nav.sub':        'Подписка',
    'nav.contact':    'Контакты',
    'nav.login':      'Войти',
    'nav.logout':     'Выйти',
    'nav.account':    'Мой аккаунт',

    'footer.tagline':       'Премиальная редакционная платформа, где встречаются мода, красота и искусство жизни.',
    'footer.col.discover':  'Открыть',
    'footer.col.corporate': 'Корпоративный',
    'footer.col.membership':'Членство',
    'footer.issue':         'Выпуск этого месяца',
    'footer.fashion':       'Мода',
    'footer.beauty':        'Красота',
    'footer.life':          'Стиль жизни',
    'footer.trends':        'Тренды',
    'footer.interviews':    'Эксклюзивные интервью',
    'footer.about':         'О нас',
    'footer.ads':           'Реклама & СМИ',
    'footer.career':        'Карьера',
    'footer.contact':       'Контакты',
    'footer.press':         'Пресса',
    'footer.plans':         'Планы',
    'footer.gift':          'Подарочная подписка',
    'footer.archive':       'Цифровой архив',
    'footer.design':        'Создать журнал',
    'footer.support':       'Поддержка',
    'footer.copy':          '© 2026 Fashiontv Magazine. Все права защищены.',
    'footer.privacy':       'Политика конфиденциальности',
    'footer.terms':         'Условия использования',
    'footer.cookie':        'Политика cookie',

    'home.hero.label':         'fashiontv magazine',
    'home.hero.title':         'Мода, Красота<br><em>& Искусство Жизни</em>',
    'home.hero.sub':           'С подиума в жизнь — премиальный журнал, где встречаются роскошь и стиль.',
    'home.hero.btn.issue':     'Выпуск этого месяца',
    'home.hero.btn.sub':       'Подписаться',

    'home.editorial.label':    'Fashiontv Magazine',
    'home.editorial.title':    'Не просто следите за модой,<br>станьте её частью',
    'home.editorial.text':     'Fashiontv Magazine предлагает изысканный редакционный опыт, объединяющий моду, красоту, культуру и стиль жизни. Каждый выпуск создаётся с вдохновляющими образами, мощными историями и вневременной эстетикой.',
    'home.editorial.feat1':    'Эксклюзивный редакционный контент',
    'home.editorial.feat2':    'Премиальный опыт журнала',
    'home.editorial.feat3':    'Цифровая и творческая платформа',
    'home.editorial.btn.dark': 'Выпуск этого месяца',
    'home.editorial.btn.sub':  'Изучить подписку',

    'home.issue.label':        'Current Issue',
    'home.issue.heading':      'fashiontv magazine <br><em>Апрельский выпуск уже вышел</em>',
    'home.issue.body':         'В этом специальном выпуске — эксклюзивные интервью с самыми престижными именами мира, глубокий анализ коллекций весна–лето 2026 и дальновидные дизайнеры, формирующие будущее моды.',
    'home.issue.li1':          '12 эксклюзивных интервью',
    'home.issue.li2':          '40+ страниц специального редакционного контента',
    'home.issue.li3':          'Анализ коллекций и тренды',
    'home.issue.btn':          'Подписаться сейчас',

    'home.cats.label':         'Открыть',
    'home.cats.heading':       'Категории',
    'home.cat1.name':          'Мода',
    'home.cat1.desc':          'Коллекции и гайды по стилю',
    'home.cat2.name':          'Красота',
    'home.cat2.desc':          'Beauty editorials',
    'home.cat3.name':          'Стиль жизни',
    'home.cat3.desc':          'Роскошный образ жизни и культура',
    'home.cat4.name':          'Тренды',
    'home.cat4.desc':          'Направление сезона',
    'home.cat5.name':          'Эксклюзивные интервью',
    'home.cat5.desc':          'Иконы моды',

    'home.casting.eyebrow':    'fashiontv magazine casting',
    'home.casting.title':      'Хотите стать моделью, манекенщицей<br>или актёром?',
    'home.casting.desc':       'Создайте заявку, наша команда проверит её. После одобрения ваше объявление увидят тысячи профессионалов — бесплатно.',
    'home.casting.btn.apply':  'Подать заявку',
    'home.casting.btn.browse': 'Изучить кастинг',

    'home.featured.label':     'Избранное',
    'home.featured.heading':   'Выбор редактора',
    'home.featured.all':       'Смотреть всё →',
    'home.read.more':          'Читать далее',

    'home.design.label':       'Творческий инструмент',
    'home.design.heading':     'Ты — звезда обложки!<br /><em>Готова к интервью?</em>',
    'home.design.body':        'Создай собственную редакционную обложку с мощной дизайн-платформой Fashiontv Magazine. Профессиональные шаблоны, корпоративный брендбук и готовый к печати результат ждут тебя.',
    'home.design.feat1':       '50+ премиальных шаблонов',
    'home.design.feat2':       'Корпоративный брендбук',
    'home.design.feat3':       'Готово к печати 300 DPI',
    'home.design.btn':         'Начать дизайн',

    'home.partners.label':     'Наши надёжные партнёры',

    'home.sub.label':          'Эксклюзивное членство',
    'home.sub.heading':        'Планы подписки',
    'home.sub.intro':          'Получите доступ ко всему контенту, полному архиву и премиальным впечатлениям.',
    'home.plan.popular':       'Самый популярный',
    'home.plan.btn.start':     'Начать',
    'home.plan.btn.get':       'Получить сейчас',

    'news.page.title':         'Новости и тренды',
    'news.cover.kicker':       'Июнь 2026 · Летний спецвыпуск',
    'news.cover.title':        'Мода,<br>Красота<br><em>& Жизнь</em>',
    'news.cover.desc':         'Сезон 2026, сформированный летней энергией — с подиума до ухода за кожей, от медленной жизни до звёздного руководства — редакционный выбор Fashiontv Magazine за июнь здесь.',
    'news.cover.btn.primary':  'Смотреть избранное',
    'news.cover.btn.ghost':    'Весь контент',
    'news.spotlight.label':    'Выбор этой недели',
    'news.spotlight.heading':  'Избранный контент',
    'news.spotlight.all':      'Смотреть всё →',
    'news.read.link':          'Читать статью →',
    'news.read.more':          'Читать далее',
    'news.filter.all':         'Все',
    'news.filter.fashion':     'Мода',
    'news.filter.beauty':      'Красота',
    'news.filter.wellness':    'Велнес',
    'news.filter.life':        'Жизнь',
    'news.filter.astro':       'Астрология',
    'news.filter.interview':   'Интервью',
    'news.load.more':          'Загрузить ещё',
    'news.sb.search':          'Поиск',
    'news.sb.popular':         'Популярные статьи',
    'news.sb.cats':            'Категории',
    'news.sb.edpick':          'Выбор редактора',
    'news.sb.newsletter':      'Бюллетень',
    'news.sb.newsletter.title':'Будьте в курсе<br><em>трендов</em>',
    'news.sb.newsletter.desc': 'Еженедельный контент о моде, красоте, велнесе и жизни прямо в ваш почтовый ящик.',
    'news.sb.newsletter.ph':   'Ваш адрес электронной почты',
    'news.sb.newsletter.btn':  'Подписаться',
    'news.sb.search.ph':       'Поиск контента…',

    'about.hero.label':        'Кто мы · С 2010 года',
    'about.hero.title':        'Редакционный<br>голос<br><span>моды</span>',
    'about.hero.desc':         'С 2010 года Fashiontv Magazine охватывает самых взыскательных читателей Турции как премиальная редакционная платформа на пересечении моды, красоты и искусства жизни.',
    'about.stat1.label':       'Лет опыта',
    'about.stat2.label':       'Читателей в месяц',
    'about.stat3.label':       'Редакционных страниц',
    'about.stat4.label':       'Эксклюзивных интервью',

    'about.story.label':       'Наша история',
    'about.story.title':       'Мы интерпретируем моду как <span>искусство</span>',
    'about.story.p1':          'Журнал — это не просто страницы; это точка зрения, голос, манифест. Fashiontv Magazine рассматривает моду не как поверхностную эстетику, а как глубокое отражение культуры, идентичности и творчества.',
    'about.story.p2':          'В каждом выпуске мы представляем самые творческие имена Турции и мира, предлагая читателям не просто тренды, но истории и видения, стоящие за ними.',
    'about.story.p3':          'С 2010 года мы объединяем ведущих дизайнеров, фотографов и авторов о моде Турции, давая моде по-настоящему премиальный голос.',

    'about.mv.label':          'Наши принципы',
    'about.mv.title':          'Миссия &amp; <span>Видение</span>',
    'about.mission.tag':       'Наша миссия',
    'about.mission.title':     'Демократизация культуры моды',
    'about.mission.text':      'Создание премиального контента, который вдохновляет и информирует наших читателей, соединяя культуру моды, красоты и образа жизни Турции с международными редакционными стандартами.',
    'about.vision.tag':        'Наше видение',
    'about.vision.title':      'Самая престижная модная платформа Турции',
    'about.vision.text':       'Стать самым читаемым и самым престижным цифровым изданием о моде в Турции к 2030 году; быть брендом, представляющим турецкую моду и дизайн на мировых платформах.',

    'about.why.label':         'Наше отличие',
    'about.why.title':         'Почему <span>fashiontv magazine?</span>',
    'about.why1.title':        'Независимая редакционная идентичность',
    'about.why1.text':         'Наш контент не подчиняется директивам рекламных агентств или брендов. Мы принимаем редакционные решения исключительно в соответствии с интересами наших читателей.',
    'about.why2.title':        'Экспертная команда и творческая сеть',
    'about.why2.text':         'Мы создаём контент из самого сердца индустрии с нашей обширной творческой сетью самых опытных редакторов моды, фотографов и стилистов Турции и Европы.',
    'about.why3.title':        'Цифровой и печатный опыт',
    'about.why3.text':         'Мы предлагаем читателям непрерывный модный опыт как через наш премиальный печатный журнал, так и через богатую цифровую платформу.',

    'about.values.label':      'Наши основные ценности',
    'about.values.title':      'За каждым материалом',
    'about.value1.title':      'Надёжность',
    'about.value1.text':       'Мы стоим за каждым своим словом.',
    'about.value2.title':      'Совершенство',
    'about.value2.text':       'Мы стремимся к высочайшему качеству в каждой детали.',
    'about.value3.title':      'Глобальная перспектива',
    'about.value3.text':       'Мы видим мир и Турцию вместе.',
    'about.value4.title':      'Творчество',
    'about.value4.text':       'Мы ставим под сомнение нормы и создаём новые перспективы.',

    'about.cta.label':         'Присоединяйтесь',
    'about.cta.title':         'Займите своё место в <span>премиальном мире</span>',
    'about.cta.desc':          'Подпишитесь сейчас, чтобы получить доступ к нашему редакционному контенту, эксклюзивным мероприятиям и привилегированным впечатлениям.',
    'about.cta.btn.primary':   'Планы подписки',
    'about.cta.btn.ghost':     'Связаться с нами',

    'contact.hero.label':      'Свяжитесь с нами',
    'contact.hero.title':      'Мы хотим<br><span>услышать</span><br>вас',
    'contact.hero.desc':       'Вы можете связаться с нами по вопросам рекламы, сотрудничества, предложений контента или подписки. Наша команда ответит вам как можно скорее.',
    'contact.info.label':      'Контактная информация',
    'contact.info.title':      'Свяжитесь с нами',
    'contact.info.intro':      'Вы можете связаться с нами по всем каналам в будние дни с 09:00 до 18:00.',
    'contact.detail.address':  'Адрес',
    'contact.detail.email':    'Эл. почта',
    'contact.detail.phone':    'Телефон',
    'contact.detail.hours':    'Рабочие часы',
    'contact.social.label':    'Социальные сети',
    'contact.form.label':      'Отправить сообщение',
    'contact.form.title':      'Написать через форму',
    'contact.field.firstname': 'Имя',
    'contact.field.lastname':  'Фамилия',
    'contact.field.email':     'Адрес эл. почты',
    'contact.field.subject':   'Тема',
    'contact.field.message':   'Ваше сообщение',
    'contact.subject.select':  'Выберите тему',
    'contact.subject.ads':     'Реклама и сотрудничество',
    'contact.subject.sub':     'Подписка',
    'contact.subject.content': 'Предложение контента',
    'contact.subject.tech':    'Техническая поддержка',
    'contact.subject.other':   'Другое',
    'contact.ph.firstname':    'Ваше имя',
    'contact.ph.lastname':     'Ваша фамилия',
    'contact.ph.email':        'example@email.com',
    'contact.ph.message':      'Напишите ваше сообщение здесь…',
    'contact.submit':          'Отправить сообщение',
    'contact.faq.label':       'Вопросы и ответы',
    'contact.faq.title':       'Часто задаваемые вопросы',

    'sub.hero.label':          'Эксклюзивные планы членства',
    'sub.hero.title':          'Премиальная<br><span>Подписка</span>',
    'sub.hero.desc':           'Получите неограниченный доступ ко всему контенту Fashiontv Magazine, эксклюзивным редакционным материалам и привилегированным впечатлениям.',
    'sub.badge.secure':        'Безопасная оплата',
    'sub.badge.cancel':        'Отмена в любое время',
    'sub.badge.instant':       'Мгновенный доступ',
    'sub.badge.premium':       'Премиальный контент',
    'sub.benefit1':            'Цифровой + печатный журнал',
    'sub.benefit2':            'Полный доступ к архиву',
    'sub.benefit3':            'Эксклюзивные приглашения на мероприятия',
    'sub.benefit4':            'Инструмент дизайна журнала',
    'sub.benefit5':            'Приоритетная поддержка',
    'sub.plans.label':         'Варианты членства',
    'sub.plans.title':         'Выберите <span>подходящий план</span>',
    'sub.plans.sub':           'Долгосрочные планы экономят больше. Отмена в любое время.',
    'sub.plan.popular':        'Самый популярный',
    'sub.plan.select':         'Выбрать план',
    'sub.plan.featured.btn':   'Получить сейчас',
    'sub.cta.title':           'Начните сегодня,<br><span>почувствуйте разницу</span>',
    'sub.cta.desc':            'Премиальный редакционный контент, эксклюзивные мероприятия и привилегированные впечатления ждут вас.',
    'sub.cta.btn.primary':     'Выбрать план',
    'sub.cta.btn.ghost':       'Сначала посмотреть контент',
    'sub.faq.label':           'Вопросы и ответы',
    'sub.faq.title':           'Часто задаваемые вопросы',

    'login.back':              'Главная',
    'login.kicker':            'Вход участника · 2026',
    'login.heading':           'Добро пожаловать<br>обратно в мир<br><em>роскоши & стиля</em>',
    'login.text':              'С подиума до искусства жизни, от редакционного контента до эксклюзивных мероприятий — добро пожаловать в премиальный мир.',
    'login.form.label':        'Вход участника',
    'login.form.title':        'Войти',
    'login.form.sub':          'Нет аккаунта?',
    'login.form.sub.link':     'Зарегистрируйтесь сейчас',
    'login.field.email':       'Адрес эл. почты',
    'login.field.password':    'Пароль',
    'login.ph.email':          'example@email.com',
    'login.ph.password':       'Введите ваш пароль',
    'login.forgot':            'Забыл пароль',
    'login.btn':               'Войти',
    'login.or':                'или',
    'login.new.account':       'Создать новый аккаунт',
    'login.security':          'Защищённое соединение с 256-bit SSL',

    'register.kicker':         'Новое членство · 2026',
    'register.heading':        'Присоединитесь к<br><em>Премиальному</em><br>миру',
    'register.text':           'Редакционный контент, эксклюзивные мероприятия и привилегированные впечатления — всё в одном членстве.',
    'register.form.label':     'Новое членство',
    'register.form.title':     'Создать аккаунт',
    'register.form.sub':       'Уже есть аккаунт?',
    'register.form.sub.link':  'Войти',
    'register.field.firstname':'Имя',
    'register.field.lastname': 'Фамилия',
    'register.field.email':    'Адрес эл. почты',
    'register.field.password': 'Пароль',
    'register.field.confirm':  'Подтверждение пароля',
    'register.ph.firstname':   'Ваше имя',
    'register.ph.lastname':    'Ваша фамилия',
    'register.ph.email':       'example@email.com',
    'register.ph.password':    'Минимум 6 символов',
    'register.ph.confirm':     'Повторите пароль',
    'register.kvkk.terms':     'Условия использования',
    'register.kvkk.privacy':   'Политику конфиденциальности',
    'register.btn':            'Создать аккаунт',
    'register.security':       'Защищённое соединение SSL · Ваши данные хранятся в зашифрованном виде',

    'account.logout':          'Выйти',

    'legal.kicker':            'Правовая информация',
    'privacy.title':           'Политика конфиденциальности',
    'terms.title':             'Условия использования',
    'cookie.title':            'Политика cookie',

    'forgot.nav.home':         'Главная',
    'forgot.nav.news':         'Новости',
    'forgot.nav.sub':          'Подписка',

    'article.back':            'Вернуться к новостям',

    'news.tape.date':          'Июнь 2026',
    'news.tape.pick':          'Выбор редакции',
    'news.tape.cats':          'Мода · Красота · Велнес · Стиль · Астрология · Интервью',
    'news.cat.count.fashion':  '12 статей',
    'news.cat.count.beauty':   '10 статей',
    'news.cat.count.wellness': '9 статей',
    'news.cat.count.life':     '8 статей',
    'news.cat.count.astro':    '8 статей',
    'news.cat.count.interview':'5 статей',
    'news.editor.label':       'Выбор редактора',
    'news.cover.date':         '12 июня 2026',
    'news.cover.vol':          'Июньский выпуск · Том 27',

    /* ── НОВОСТИ — СТАТЬИ ── */
    'news.art.moda1.title':     'Летний сезон 2026: Мощное возвращение минимализма',
    'news.art.moda1.excerpt':   'Общий язык этого сезона на подиумах Милана, Парижа и Копенгагена: чёткие линии, премиальные ткани и манифест вневременной простоты.',
    'news.art.guzellik1.title': 'Процедура Glazed Skin: Сияющий вид кожи этим летом',
    'news.art.guzellik1.excerpt':'Самый обсуждаемый тренд естественного сияния лета: гиалуроновая кислота, керамиды и пептиды.',
    'news.art.wellness1.title': 'Восход медленной жизни: новая роскошь 2026 года',
    'news.art.wellness1.excerpt':'Подход slow living занял центральное место в мире велнеса 2026 года. Душевный покой — новая роскошь.',
    'news.art.yasam1.title':    'Новое золотое правило ухода за кожей: меньше продуктов, больше эффекта',
    'news.art.yasam1.excerpt':  'По мнению дерматологов, выбор правильного продукта гораздо эффективнее длинных и сложных процедур ухода.',
    'news.art.astro1.title':    'Гороскоп на июнь: начинается летняя энергия',
    'news.art.astro1.excerpt':  'Под влиянием Венеры и Марса в июне 2026 года все знаки зодиака ощутят мощную энергию новых начинаний.',
    'news.art.roportaj1.title': 'Эксклюзивное интервью с Серрой Кайа',
    'news.art.roportaj1.excerpt':'Влиятельная фигура в мире моды Серра Кайа рассказала о своей философии стиля, источниках вдохновения и пути в мире моды.',
    'news.art.moda2.title':     'Новое видение Valentino: трансформация художественного нарратива в роскоши',
    'news.art.moda2.excerpt':   'Коллекция нового креативного директора знаменует кардинальный перелом в мире моды.',
    'news.art.guzellik2.title': 'Точка встречи классики и современности в свадебном макияже',
    'news.art.guzellik2.excerpt':'Полное руководство по самым популярным стилям и продуктам для макияжа в свадебный сезон.',
    'news.art.wellness2.title': 'Травяной ритуал сна: 7 шагов к глубокому и качественному сну',
    'news.art.wellness2.excerpt':'Преобразите свой ночной ритуал с помощью натуральных методов и рекомендаций экспертов для улучшения качества сна.',
    'news.art.yasam2.title':    'Медленные путешествия — это роскошь? Новый способ открытий fashion-редакторов',
    'news.art.yasam2.excerpt':  'Глубокие, осмысленные путешествия, пришедшие на смену стремительным турам, стали новым символом престижа.',
    'news.art.astro2.title':    'Гороскоп на июль: время перемен',
    'news.art.astro2.excerpt':  'Под влиянием Юпитера в июле 2026 года грядут большие перемены.',
    'news.art.roportaj2.title': 'Дизайнер Бора Аксу о моде, идентичности и Стамбуле',
    'news.art.roportaj2.excerpt':'Турецкий дизайнер, покоривший лондонские подиумы, рассказал о том, как культурные корни превращаются в язык моды.',

    /* ── SPOTLIGHT КАРТОЧКИ ── */
    'news.spotlight.moda.title':    'Капсульный гардероб на лето: сильный стиль из 10 предметов',
    'news.spotlight.wellness.title':'6 небольших привычек, которые изменят утренний ритуал',

    /* ── ПОЛОСА РЕДАКТОРА ── */
    'news.editor.link1':        'Тренды моды 2026',
    'news.editor.link2':        'Уход за кожей',
    'news.editor.link3':        'Гороскоп на июнь',
    'news.editor.link4':        'Минималистичная жизнь',
    'news.editor.link5':        'Эксклюзивные интервью',

    'sub.hero.desc':           'Получите неограниченный доступ ко всему контенту Fashiontv Magazine, эксклюзивным редакционным материалам и привилегированным впечатлениям.',
    'sub.plans.sub':           'Долгосрочные планы экономят больше. Отмена в любое время.',
    'sub.period.3m':           '3 месяца',
    'sub.period.6m':           '6 месяцев',
    'sub.period.9m':           '9 месяцев',
    'sub.period.1y':           '1 год',
    'sub.period.3y':           '3 года',
    'sub.period.5y':           '5 лет',
    'sub.cycle.3m':            '/ 3 мес.',
    'sub.cycle.6m':            '/ 6 мес.',
    'sub.cycle.9m':            '/ 9 мес.',
    'sub.cycle.1y':            '/ год',
    'sub.cycle.3y':            '/ 3 года',
    'sub.cycle.5y':            '/ 5 лет',
    'sub.saving.16':           'Скидка 16%',
    'sub.saving.22':           'Скидка 22%',
    'sub.saving.29':           'Скидка 29%',
    'sub.saving.34':           'Скидка 34%',
    'sub.saving.40':           'Скидка 40%',
    'sub.feat.digital':        'Цифровой доступ',
    'sub.feat.archive.3m':     'Архив за 3 месяца',
    'sub.feat.newsletter':     'Еженедельный бюллетень',
    'sub.feat.digital_print':  'Цифровой + Печатный журнал',
    'sub.feat.archive.6m':     'Архив за 6 месяцев',
    'sub.feat.events':         'Приглашения на эксклюзивные мероприятия',
    'sub.feat.archive.9m':     'Архив за 9 месяцев',
    'sub.feat.design_tool':    'Инструмент дизайна журнала',
    'sub.feat.full_archive':   'Полный доступ к архиву',
    'sub.feat.priority':       'Приоритетная поддержка',
    'sub.feat.all_premium':    'Все преимущества Premium',
    'sub.feat.cover_gift':     'Эксклюзивный подарок с обложкой',
    'sub.feat.vip_events':     'VIP-доступ к мероприятиям',
    'sub.feat.style_advisor':  'Персональный стилист',
    'sub.feat.all_elite':      'Все преимущества Elite',
    'sub.feat.print_col':      'Эксклюзивная коллекция изданий',
    'sub.feat.workshop':       'Мастерская и мастер-класс',
    'sub.feat.brand_partner':  'Партнёрство с брендом',
    'sub.feat.welcome_kit':    'Люксовый приветственный набор',
    'sub.cta.desc':            'Премиальные редакционные материалы, эксклюзивные мероприятия и привилегированный опыт ждут вас.',
    'sub.faq.q1': 'Могу ли я отменить подписку в любое время?',
    'sub.faq.a1': 'Да. Вы можете отменить подписку через свой аккаунт в любое время. Отмена вступает в силу по окончании текущего периода; до этого момента вы продолжаете пользоваться всеми преимуществами.',
    'sub.faq.q2': 'Какие способы оплаты вы принимаете?',
    'sub.faq.a2': 'Вы можете оплатить картами Visa, Mastercard и American Express. Все транзакции проходят через защищённую инфраструктуру с шифрованием SSL 256 бит.',
    'sub.faq.q3': 'Когда я получу доступ к цифровому контенту?',
    'sub.faq.a3': 'Доступ к цифровому контенту предоставляется сразу после подтверждения оплаты. Печатный журнал доставляется по указанному адресу в течение нескольких рабочих дней.',
    'sub.faq.q4': 'Могу ли я позже перейти на более высокий план?',
    'sub.faq.a4': 'Вы можете перейти на любой план после окончания текущего периода подписки. Для досрочного перехода обратитесь в службу поддержки.',
    'sub.faq.q5': 'В каких планах есть инструмент дизайна журнала?',
    'sub.faq.a5': 'Инструмент дизайна журнала доступен во всех планах от Classic и выше (Classic, Premium, Elite, Maison).',
  },
};

/* ═══════════════════════════════════════════════════════════
   LANG META
   ═══════════════════════════════════════════════════════════ */
const SITE_LANG_META = {
  tr: { flag: '🇹🇷', name: 'Türkçe',  code: 'TR' },
  en: { flag: '🇬🇧', name: 'English',  code: 'EN' },
  ru: { flag: '🇷🇺', name: 'Русский',  code: 'RU' },
};

/* ═══════════════════════════════════════════════════════════
   I18N ENGINE
   ═══════════════════════════════════════════════════════════ */
const I18n = {
  _lang: 'tr',

  init() {
    const saved = localStorage.getItem('ftv_site_lang') || 'tr';
    this.setLang(saved, false);
    this._initDropdown();
  },

  setLang(lang, save = true) {
    if (!LANGS[lang]) return;
    this._lang = lang;
    if (save) localStorage.setItem('ftv_site_lang', lang);
    document.documentElement.lang = lang;
    this.applyAll();
    this.updateSwitcher();
    /* Dropdown'u kapat */
    document.querySelectorAll('.lang-switcher').forEach(s => s.classList.remove('open'));
  },

  t(key) {
    return LANGS[this._lang][key] || LANGS['tr'][key] || key;
  },

  applyAll() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.dataset.i18n;
      const val = this.t(key);
      if (val.includes('<br>') || val.includes('<em>') || val.includes('<span>') || val.includes('&amp;')) {
        el.innerHTML = val;
      } else {
        el.textContent = val;
      }
    });
    document.querySelectorAll('[data-i18n-ph]').forEach(el => {
      const val = this.t(el.dataset.i18nPh);
      el.placeholder = val;
      el.setAttribute('placeholder', val);
    });
    document.querySelectorAll('[data-i18n-opt]').forEach(el => {
      const key = el.dataset.i18nOpt;
      const val = this.t(key);
      el.textContent = val;
    });
  },

  updateSwitcher() {
    const m = SITE_LANG_META[this._lang];
    document.querySelectorAll('.lang-flag-current').forEach(el => el.textContent = m.flag);
    document.querySelectorAll('.lang-code-current').forEach(el => el.textContent = m.code);
    document.querySelectorAll('.lang-opt').forEach(btn => {
      btn.classList.toggle('active', btn.dataset.lang === this._lang);
    });
  },

  _initDropdown() {
    document.querySelectorAll('.lang-switcher').forEach(sw => {
      const trigger = sw.querySelector('.lang-current');
      if (!trigger) return;
      trigger.addEventListener('click', (e) => {
        e.stopPropagation();
        sw.classList.toggle('open');
      });
    });
    document.querySelectorAll('.lang-opt').forEach(btn => {
      btn.addEventListener('click', (e) => {
        e.stopPropagation();
        I18n.setLang(btn.dataset.lang);
      });
    });
    document.addEventListener('click', () => {
      document.querySelectorAll('.lang-switcher').forEach(s => s.classList.remove('open'));
    });
  },
};

/* DOM zaten yüklüyse hemen çalıştır, değilse bekle */
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', () => I18n.init());
} else {
  I18n.init();
}
